### PR TITLE
CA-216671: Use JSON-RPC v2 to communicate with the PVS proxy

### PR DESCRIPTION
**Pull request by robhoes**

### CODE REVIEW

**Comment by robhoes** [comment]
@lindig This is a simple fix for a communication issue with the PVS daemon.

**Comment by lindig** [comment]
Why do you need the new `unit` argument in `with_rpc`? Otherwise this looks good.

**Comment by robhoes** [comment]
@lindig I needed to add a positional argument for the optional argument to work.

**Comment by lindig** [comment]
I would have considered to take away the label for `call` since it has a descriptive type. Anyway, it's fine now.

**Pull request merged**
